vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        uploads:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: 
                service: Vich\UploaderBundle\Naming\Base64Namer
                options: { length: 50 }
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'property.id', transliterate: true }     
